/var/runtime/botocore/vendored/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.4) or chardet (4.0.0) doesn't match a supported version!
RequestsDependencyWarning)
START RequestId: XXXX Version: $LATEST
{"m": "aws.lambda.enhanced.invocations", "v": 1, "e": XXXX, "t": ["region:us-east-1", "account_id:XXXX", "functionname:integration-dev-http-requests_python36", "resource:integration-dev-http-requests_python36", "cold_start:true", "memorysize:1024", "runtime:python3.6", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python36_2.XX.0"]}
HTTP GET https://ip-ranges.datadoghq.com/ Headers: ["Accept-Encoding:gzip, deflate", "Accept:*/*", "Connection:keep-alive", "User-Agent:python-requests/2.25.1", "x-datadog-parent-id:XXXX", "x-datadog-sampling-priority:1", "x-datadog-trace-id:XXXX"] Data: {}
HTTP GET https://ip-ranges.datadoghq.eu/ Headers: ["Accept-Encoding:gzip, deflate", "Accept:*/*", "Connection:keep-alive", "User-Agent:python-requests/2.25.1", "x-datadog-parent-id:XXXX", "x-datadog-sampling-priority:1", "x-datadog-trace-id:XXXX"] Data: {}
2021-03-24 18:59:29.330 (-04:00)	f78ef4e0-830f-4e14-90f4-20a5766f8de7	[ERROR]	[dd.trace_id=12122548186595979423 dd.span_id=2732310535487830439]	Error flushing metrics and events
Traceback (most recent call last):
  File "/opt/python/lib/python3.6/site-packages/datadog/threadstats/base.py", line 343, in flush
    self.reporter.flush_distributions(dists)
  File "/opt/python/lib/python3.6/site-packages/datadog/threadstats/reporters.py", line 24, in flush_distributions
    api.Distribution.send(distributions, compress_payload=self.compress_payload)
  File "/opt/python/lib/python3.6/site-packages/datadog/api/distributions.py", line 43, in send
    attach_host_name=attach_host_name, compress_payload=compress_payload, **series_dict
  File "/opt/python/lib/python3.6/site-packages/datadog/api/resources.py", line 88, in send
    compress_payload=compress_payload
  File "/opt/python/lib/python3.6/site-packages/datadog/api/api_client.py", line 166, in submit
    proxies=_proxies, verify=_cacert
  File "/opt/python/lib/python3.6/site-packages/datadog/api/http_client.py", line 100, in request
    proxies=proxies, verify=verify)
  File "/opt/python/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/lib/python3.6/site-packages/ddtrace/contrib/requests/connection.py", line 95, in _wrap_send
    response = func(*args, **kwargs)
  File "/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py", line 133, in _log_request
    _print_request_string(request)
  File "/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py", line 147, in _print_request_string
    data_dict = json.loads(data)
  File "/var/lang/lib/python3.6/json/__init__.py", line 349, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte{"traces": [[{"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "integration-dev-http-requests_python36", "name": "aws.lambda", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "runtime-id": "XXXX", "cold_start": "true", "function_arn": "arn:aws:lambda:us-east-1:601427279990:function:integration-dev-http-requests_python36", "function_version": "$LATEST", "request_id": "XXXX", "resource_names": "integration-dev-http-requests_python36", "datadog_lambda": "X.X.X", "dd_trace": "X.X.X", "function_trigger.event_source": "api-gateway", "function_trigger.event_source_arn": "arn:aws:apigateway:us-east-1::/restapis/wt6mne2s9k/stages/test", "http.method": "GET", "http.status_code": "200"}, "metrics": {"_dd.agent_psr": 1.0, "system.pid": XXXX, "_sampling_priority_v1": 1}, "type": "serverless"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "GET", "http.url": "https://ip-ranges.datadoghq.com/", "http.status_code": "200"}, "metrics": {"_dd.measured": 1}, "type": "http"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "GET", "http.url": "https://ip-ranges.datadoghq.eu/", "http.status_code": "200"}, "metrics": {"_dd.measured": 1}, "type": "http"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 1, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "POST", "http.url": "https://api.datadoghq.com/api/v1/distribution_points", "error.msg": "'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte", "error.type": "builtins.UnicodeDecodeError", "error.stack": "Traceback (most recent call last):\n  File \"/opt/python/lib/python3.6/site-packages/ddtrace/contrib/requests/connection.py\", line 95, in _wrap_send\n    response = func(*args, **kwargs)\n  File \"/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py\", line 133, in _log_request\n    _print_request_string(request)\n  File \"/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py\", line 147, in _print_request_string\n    data_dict = json.loads(data)\n  File \"/var/lang/lib/python3.6/json/__init__.py\", line 349, in loads\n    s = s.decode(detect_encoding(s), 'surrogatepass')\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte\n"}, "metrics": {"_dd.measured": 1}, "type": "http"}]]}
END RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	Init Duration: XXXX ms	
XRAY TraceId: XXXX	SegmentId: XXXX	Sampled: true	
START RequestId: XXXX Version: $LATEST
{"m": "aws.lambda.enhanced.invocations", "v": 1, "e": XXXX, "t": ["region:us-east-1", "account_id:XXXX", "functionname:integration-dev-http-requests_python36", "resource:integration-dev-http-requests_python36", "cold_start:false", "memorysize:1024", "runtime:python3.6", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python36_2.XX.0"]}
HTTP GET https://ip-ranges.datadoghq.com/ Headers: ["Accept-Encoding:gzip, deflate", "Accept:*/*", "Connection:keep-alive", "User-Agent:python-requests/2.25.1", "x-datadog-parent-id:XXXX", "x-datadog-sampling-priority:1", "x-datadog-trace-id:XXXX"] Data: {}
HTTP GET https://ip-ranges.datadoghq.eu/ Headers: ["Accept-Encoding:gzip, deflate", "Accept:*/*", "Connection:keep-alive", "User-Agent:python-requests/2.25.1", "x-datadog-parent-id:XXXX", "x-datadog-sampling-priority:1", "x-datadog-trace-id:XXXX"] Data: {}
2021-03-24 18:59:30.516 (-04:00)	04edd9ef-8f8d-4c42-9a13-6e38a7831a33	[ERROR]	[dd.trace_id=14961919373628698867 dd.span_id=327470228677468396]	Error flushing metrics and events
Traceback (most recent call last):
  File "/opt/python/lib/python3.6/site-packages/datadog/threadstats/base.py", line 343, in flush
    self.reporter.flush_distributions(dists)
  File "/opt/python/lib/python3.6/site-packages/datadog/threadstats/reporters.py", line 24, in flush_distributions
    api.Distribution.send(distributions, compress_payload=self.compress_payload)
  File "/opt/python/lib/python3.6/site-packages/datadog/api/distributions.py", line 43, in send
    attach_host_name=attach_host_name, compress_payload=compress_payload, **series_dict
  File "/opt/python/lib/python3.6/site-packages/datadog/api/resources.py", line 88, in send
    compress_payload=compress_payload
  File "/opt/python/lib/python3.6/site-packages/datadog/api/api_client.py", line 166, in submit
    proxies=_proxies, verify=_cacert
  File "/opt/python/lib/python3.6/site-packages/datadog/api/http_client.py", line 100, in request
    proxies=proxies, verify=verify)
  File "/opt/python/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/lib/python3.6/site-packages/ddtrace/contrib/requests/connection.py", line 95, in _wrap_send
    response = func(*args, **kwargs)
  File "/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py", line 133, in _log_request
    _print_request_string(request)
  File "/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py", line 147, in _print_request_string
    data_dict = json.loads(data)
  File "/var/lang/lib/python3.6/json/__init__.py", line 349, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte{"traces": [[{"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "integration-dev-http-requests_python36", "name": "aws.lambda", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "runtime-id": "XXXX", "cold_start": "false", "function_arn": "arn:aws:lambda:us-east-1:601427279990:function:integration-dev-http-requests_python36", "function_version": "$LATEST", "request_id": "XXXX", "resource_names": "integration-dev-http-requests_python36", "datadog_lambda": "X.X.X", "dd_trace": "X.X.X", "function_trigger.event_source": "sns", "function_trigger.event_source_arn": "arn:aws:sns:us-east-2:123456789012:sns-lambda"}, "metrics": {"_dd.agent_psr": 1.0, "system.pid": XXXX, "_sampling_priority_v1": 1}, "type": "serverless"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "GET", "http.url": "https://ip-ranges.datadoghq.com/", "http.status_code": "200"}, "metrics": {"_dd.measured": 1}, "type": "http"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "GET", "http.url": "https://ip-ranges.datadoghq.eu/", "http.status_code": "200"}, "metrics": {"_dd.measured": 1}, "type": "http"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 1, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "POST", "http.url": "https://api.datadoghq.com/api/v1/distribution_points", "error.msg": "'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte", "error.type": "builtins.UnicodeDecodeError", "error.stack": "Traceback (most recent call last):\n  File \"/opt/python/lib/python3.6/site-packages/ddtrace/contrib/requests/connection.py\", line 95, in _wrap_send\n    response = func(*args, **kwargs)\n  File \"/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py\", line 133, in _log_request\n    _print_request_string(request)\n  File \"/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py\", line 147, in _print_request_string\n    data_dict = json.loads(data)\n  File \"/var/lang/lib/python3.6/json/__init__.py\", line 349, in loads\n    s = s.decode(detect_encoding(s), 'surrogatepass')\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte\n"}, "metrics": {"_dd.measured": 1}, "type": "http"}]]}
END RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	
XRAY TraceId: XXXX	SegmentId: XXXX	Sampled: true	
START RequestId: XXXX Version: $LATEST
{"m": "aws.lambda.enhanced.invocations", "v": 1, "e": XXXX, "t": ["region:us-east-1", "account_id:XXXX", "functionname:integration-dev-http-requests_python36", "resource:integration-dev-http-requests_python36", "cold_start:false", "memorysize:1024", "runtime:python3.6", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python36_2.XX.0"]}
HTTP GET https://ip-ranges.datadoghq.com/ Headers: ["Accept-Encoding:gzip, deflate", "Accept:*/*", "Connection:keep-alive", "User-Agent:python-requests/2.25.1", "x-datadog-parent-id:XXXX", "x-datadog-sampling-priority:1", "x-datadog-trace-id:XXXX"] Data: {}
HTTP GET https://ip-ranges.datadoghq.eu/ Headers: ["Accept-Encoding:gzip, deflate", "Accept:*/*", "Connection:keep-alive", "User-Agent:python-requests/2.25.1", "x-datadog-parent-id:XXXX", "x-datadog-sampling-priority:1", "x-datadog-trace-id:XXXX"] Data: {}
2021-03-24 18:59:31.998 (-04:00)	596412b8-16e7-496e-92d5-2237120df6e5	[ERROR]	[dd.trace_id=666 dd.span_id=10991926048721366458]	Error flushing metrics and events
Traceback (most recent call last):
  File "/opt/python/lib/python3.6/site-packages/datadog/threadstats/base.py", line 343, in flush
    self.reporter.flush_distributions(dists)
  File "/opt/python/lib/python3.6/site-packages/datadog/threadstats/reporters.py", line 24, in flush_distributions
    api.Distribution.send(distributions, compress_payload=self.compress_payload)
  File "/opt/python/lib/python3.6/site-packages/datadog/api/distributions.py", line 43, in send
    attach_host_name=attach_host_name, compress_payload=compress_payload, **series_dict
  File "/opt/python/lib/python3.6/site-packages/datadog/api/resources.py", line 88, in send
    compress_payload=compress_payload
  File "/opt/python/lib/python3.6/site-packages/datadog/api/api_client.py", line 166, in submit
    proxies=_proxies, verify=_cacert
  File "/opt/python/lib/python3.6/site-packages/datadog/api/http_client.py", line 100, in request
    proxies=proxies, verify=verify)
  File "/opt/python/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/lib/python3.6/site-packages/ddtrace/contrib/requests/connection.py", line 95, in _wrap_send
    response = func(*args, **kwargs)
  File "/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py", line 133, in _log_request
    _print_request_string(request)
  File "/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py", line 147, in _print_request_string
    data_dict = json.loads(data)
  File "/var/lang/lib/python3.6/json/__init__.py", line 349, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte{"traces": [[{"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "integration-dev-http-requests_python36", "name": "aws.lambda", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "runtime-id": "XXXX", "cold_start": "false", "function_arn": "arn:aws:lambda:us-east-1:601427279990:function:integration-dev-http-requests_python36", "function_version": "$LATEST", "request_id": "XXXX", "resource_names": "integration-dev-http-requests_python36", "datadog_lambda": "X.X.X", "dd_trace": "X.X.X", "function_trigger.event_source": "sqs", "function_trigger.event_source_arn": "arn:aws:sqs:us-east-2:123456789012:my-queue"}, "metrics": {"system.pid": XXXX, "_sampling_priority_v1": 1}, "type": "serverless"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "GET", "http.url": "https://ip-ranges.datadoghq.com/", "http.status_code": "200"}, "metrics": {"_dd.measured": 1}, "type": "http"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "GET", "http.url": "https://ip-ranges.datadoghq.eu/", "http.status_code": "200"}, "metrics": {"_dd.measured": 1}, "type": "http"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 1, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "POST", "http.url": "https://api.datadoghq.com/api/v1/distribution_points", "error.msg": "'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte", "error.type": "builtins.UnicodeDecodeError", "error.stack": "Traceback (most recent call last):\n  File \"/opt/python/lib/python3.6/site-packages/ddtrace/contrib/requests/connection.py\", line 95, in _wrap_send\n    response = func(*args, **kwargs)\n  File \"/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py\", line 133, in _log_request\n    _print_request_string(request)\n  File \"/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py\", line 147, in _print_request_string\n    data_dict = json.loads(data)\n  File \"/var/lang/lib/python3.6/json/__init__.py\", line 349, in loads\n    s = s.decode(detect_encoding(s), 'surrogatepass')\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte\n"}, "metrics": {"_dd.measured": 1}, "type": "http"}]]}
END RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	
XRAY TraceId: XXXX	SegmentId: XXXX	Sampled: true	
/var/runtime/botocore/vendored/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.4) or chardet (4.0.0) doesn't match a supported version!
RequestsDependencyWarning)
START RequestId: XXXX Version: $LATEST
{"m": "aws.lambda.enhanced.invocations", "v": 1, "e": XXXX, "t": ["region:us-east-1", "account_id:XXXX", "functionname:integration-dev-http-requests_python36", "resource:integration-dev-http-requests_python36", "cold_start:true", "memorysize:1024", "runtime:python3.6", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python36_2.XX.0"]}
HTTP GET https://ip-ranges.datadoghq.com/ Headers: ["Accept-Encoding:gzip, deflate", "Accept:*/*", "Connection:keep-alive", "User-Agent:python-requests/2.25.1", "x-datadog-parent-id:XXXX", "x-datadog-sampling-priority:1", "x-datadog-trace-id:XXXX"] Data: {}
HTTP GET https://ip-ranges.datadoghq.eu/ Headers: ["Accept-Encoding:gzip, deflate", "Accept:*/*", "Connection:keep-alive", "User-Agent:python-requests/2.25.1", "x-datadog-parent-id:XXXX", "x-datadog-sampling-priority:1", "x-datadog-trace-id:XXXX"] Data: {}
2021-03-24 19:21:04.401 (-04:00)	80c51808-0f11-4149-b852-e18ed95f2bb1	[ERROR]	[dd.trace_id=11091958679382837808 dd.span_id=356596925768357092]	Error flushing metrics and events
Traceback (most recent call last):
  File "/opt/python/lib/python3.6/site-packages/datadog/threadstats/base.py", line 343, in flush
    self.reporter.flush_distributions(dists)
  File "/opt/python/lib/python3.6/site-packages/datadog/threadstats/reporters.py", line 24, in flush_distributions
    api.Distribution.send(distributions, compress_payload=self.compress_payload)
  File "/opt/python/lib/python3.6/site-packages/datadog/api/distributions.py", line 43, in send
    attach_host_name=attach_host_name, compress_payload=compress_payload, **series_dict
  File "/opt/python/lib/python3.6/site-packages/datadog/api/resources.py", line 88, in send
    compress_payload=compress_payload
  File "/opt/python/lib/python3.6/site-packages/datadog/api/api_client.py", line 166, in submit
    proxies=_proxies, verify=_cacert
  File "/opt/python/lib/python3.6/site-packages/datadog/api/http_client.py", line 100, in request
    proxies=proxies, verify=verify)
  File "/opt/python/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/lib/python3.6/site-packages/ddtrace/contrib/requests/connection.py", line 95, in _wrap_send
    response = func(*args, **kwargs)
  File "/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py", line 133, in _log_request
    _print_request_string(request)
  File "/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py", line 147, in _print_request_string
    data_dict = json.loads(data)
  File "/var/lang/lib/python3.6/json/__init__.py", line 349, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte{"traces": [[{"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "integration-dev-http-requests_python36", "name": "aws.lambda", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "runtime-id": "XXXX", "cold_start": "true", "function_arn": "arn:aws:lambda:us-east-1:601427279990:function:integration-dev-http-requests_python36", "function_version": "$LATEST", "request_id": "XXXX", "resource_names": "integration-dev-http-requests_python36", "datadog_lambda": "X.X.X", "dd_trace": "X.X.X", "function_trigger.event_source": "api-gateway", "function_trigger.event_source_arn": "arn:aws:apigateway:us-east-1::/restapis/wt6mne2s9k/stages/test", "http.method": "GET", "http.status_code": "200"}, "metrics": {"_dd.agent_psr": 1.0, "system.pid": XXXX, "_sampling_priority_v1": 1}, "type": "serverless"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "GET", "http.url": "https://ip-ranges.datadoghq.com/", "http.status_code": "200"}, "metrics": {"_dd.measured": 1}, "type": "http"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "GET", "http.url": "https://ip-ranges.datadoghq.eu/", "http.status_code": "200"}, "metrics": {"_dd.measured": 1}, "type": "http"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 1, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "POST", "http.url": "https://api.datadoghq.com/api/v1/distribution_points", "error.msg": "'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte", "error.type": "builtins.UnicodeDecodeError", "error.stack": "Traceback (most recent call last):\n  File \"/opt/python/lib/python3.6/site-packages/ddtrace/contrib/requests/connection.py\", line 95, in _wrap_send\n    response = func(*args, **kwargs)\n  File \"/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py\", line 133, in _log_request\n    _print_request_string(request)\n  File \"/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py\", line 147, in _print_request_string\n    data_dict = json.loads(data)\n  File \"/var/lang/lib/python3.6/json/__init__.py\", line 349, in loads\n    s = s.decode(detect_encoding(s), 'surrogatepass')\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte\n"}, "metrics": {"_dd.measured": 1}, "type": "http"}]]}
END RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	Init Duration: XXXX ms	
XRAY TraceId: XXXX	SegmentId: XXXX	Sampled: true	
START RequestId: XXXX Version: $LATEST
{"m": "aws.lambda.enhanced.invocations", "v": 1, "e": XXXX, "t": ["region:us-east-1", "account_id:XXXX", "functionname:integration-dev-http-requests_python36", "resource:integration-dev-http-requests_python36", "cold_start:false", "memorysize:1024", "runtime:python3.6", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python36_2.XX.0"]}
HTTP GET https://ip-ranges.datadoghq.com/ Headers: ["Accept-Encoding:gzip, deflate", "Accept:*/*", "Connection:keep-alive", "User-Agent:python-requests/2.25.1", "x-datadog-parent-id:XXXX", "x-datadog-sampling-priority:1", "x-datadog-trace-id:XXXX"] Data: {}
HTTP GET https://ip-ranges.datadoghq.eu/ Headers: ["Accept-Encoding:gzip, deflate", "Accept:*/*", "Connection:keep-alive", "User-Agent:python-requests/2.25.1", "x-datadog-parent-id:XXXX", "x-datadog-sampling-priority:1", "x-datadog-trace-id:XXXX"] Data: {}
2021-03-24 19:21:05.916 (-04:00)	0398f67e-2a9b-420f-b571-cadcaf648536	[ERROR]	[dd.trace_id=2883045584705332068 dd.span_id=11805092876129500859]	Error flushing metrics and events
Traceback (most recent call last):
  File "/opt/python/lib/python3.6/site-packages/datadog/threadstats/base.py", line 343, in flush
    self.reporter.flush_distributions(dists)
  File "/opt/python/lib/python3.6/site-packages/datadog/threadstats/reporters.py", line 24, in flush_distributions
    api.Distribution.send(distributions, compress_payload=self.compress_payload)
  File "/opt/python/lib/python3.6/site-packages/datadog/api/distributions.py", line 43, in send
    attach_host_name=attach_host_name, compress_payload=compress_payload, **series_dict
  File "/opt/python/lib/python3.6/site-packages/datadog/api/resources.py", line 88, in send
    compress_payload=compress_payload
  File "/opt/python/lib/python3.6/site-packages/datadog/api/api_client.py", line 166, in submit
    proxies=_proxies, verify=_cacert
  File "/opt/python/lib/python3.6/site-packages/datadog/api/http_client.py", line 100, in request
    proxies=proxies, verify=verify)
  File "/opt/python/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/lib/python3.6/site-packages/ddtrace/contrib/requests/connection.py", line 95, in _wrap_send
    response = func(*args, **kwargs)
  File "/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py", line 133, in _log_request
    _print_request_string(request)
  File "/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py", line 147, in _print_request_string
    data_dict = json.loads(data)
  File "/var/lang/lib/python3.6/json/__init__.py", line 349, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte{"traces": [[{"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "integration-dev-http-requests_python36", "name": "aws.lambda", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "runtime-id": "XXXX", "cold_start": "false", "function_arn": "arn:aws:lambda:us-east-1:601427279990:function:integration-dev-http-requests_python36", "function_version": "$LATEST", "request_id": "XXXX", "resource_names": "integration-dev-http-requests_python36", "datadog_lambda": "X.X.X", "dd_trace": "X.X.X", "function_trigger.event_source": "sns", "function_trigger.event_source_arn": "arn:aws:sns:us-east-2:123456789012:sns-lambda"}, "metrics": {"_dd.agent_psr": 1.0, "system.pid": XXXX, "_sampling_priority_v1": 1}, "type": "serverless"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "GET", "http.url": "https://ip-ranges.datadoghq.com/", "http.status_code": "200"}, "metrics": {"_dd.measured": 1}, "type": "http"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "GET", "http.url": "https://ip-ranges.datadoghq.eu/", "http.status_code": "200"}, "metrics": {"_dd.measured": 1}, "type": "http"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 1, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "POST", "http.url": "https://api.datadoghq.com/api/v1/distribution_points", "error.msg": "'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte", "error.type": "builtins.UnicodeDecodeError", "error.stack": "Traceback (most recent call last):\n  File \"/opt/python/lib/python3.6/site-packages/ddtrace/contrib/requests/connection.py\", line 95, in _wrap_send\n    response = func(*args, **kwargs)\n  File \"/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py\", line 133, in _log_request\n    _print_request_string(request)\n  File \"/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py\", line 147, in _print_request_string\n    data_dict = json.loads(data)\n  File \"/var/lang/lib/python3.6/json/__init__.py\", line 349, in loads\n    s = s.decode(detect_encoding(s), 'surrogatepass')\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte\n"}, "metrics": {"_dd.measured": 1}, "type": "http"}]]}
END RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	
XRAY TraceId: XXXX	SegmentId: XXXX	Sampled: true	
START RequestId: XXXX Version: $LATEST
{"m": "aws.lambda.enhanced.invocations", "v": 1, "e": XXXX, "t": ["region:us-east-1", "account_id:XXXX", "functionname:integration-dev-http-requests_python36", "resource:integration-dev-http-requests_python36", "cold_start:false", "memorysize:1024", "runtime:python3.6", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python36_2.XX.0"]}
HTTP GET https://ip-ranges.datadoghq.com/ Headers: ["Accept-Encoding:gzip, deflate", "Accept:*/*", "Connection:keep-alive", "User-Agent:python-requests/2.25.1", "x-datadog-parent-id:XXXX", "x-datadog-sampling-priority:1", "x-datadog-trace-id:XXXX"] Data: {}
HTTP GET https://ip-ranges.datadoghq.eu/ Headers: ["Accept-Encoding:gzip, deflate", "Accept:*/*", "Connection:keep-alive", "User-Agent:python-requests/2.25.1", "x-datadog-parent-id:XXXX", "x-datadog-sampling-priority:1", "x-datadog-trace-id:XXXX"] Data: {}
2021-03-24 19:21:07.373 (-04:00)	6004145b-6f0d-4498-bf1e-176a8e6eef51	[ERROR]	[dd.trace_id=666 dd.span_id=4364139850915738040]	Error flushing metrics and events
Traceback (most recent call last):
  File "/opt/python/lib/python3.6/site-packages/datadog/threadstats/base.py", line 343, in flush
    self.reporter.flush_distributions(dists)
  File "/opt/python/lib/python3.6/site-packages/datadog/threadstats/reporters.py", line 24, in flush_distributions
    api.Distribution.send(distributions, compress_payload=self.compress_payload)
  File "/opt/python/lib/python3.6/site-packages/datadog/api/distributions.py", line 43, in send
    attach_host_name=attach_host_name, compress_payload=compress_payload, **series_dict
  File "/opt/python/lib/python3.6/site-packages/datadog/api/resources.py", line 88, in send
    compress_payload=compress_payload
  File "/opt/python/lib/python3.6/site-packages/datadog/api/api_client.py", line 166, in submit
    proxies=_proxies, verify=_cacert
  File "/opt/python/lib/python3.6/site-packages/datadog/api/http_client.py", line 100, in request
    proxies=proxies, verify=verify)
  File "/opt/python/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/lib/python3.6/site-packages/ddtrace/contrib/requests/connection.py", line 95, in _wrap_send
    response = func(*args, **kwargs)
  File "/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py", line 133, in _log_request
    _print_request_string(request)
  File "/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py", line 147, in _print_request_string
    data_dict = json.loads(data)
  File "/var/lang/lib/python3.6/json/__init__.py", line 349, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte{"traces": [[{"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "integration-dev-http-requests_python36", "name": "aws.lambda", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "runtime-id": "XXXX", "cold_start": "false", "function_arn": "arn:aws:lambda:us-east-1:601427279990:function:integration-dev-http-requests_python36", "function_version": "$LATEST", "request_id": "XXXX", "resource_names": "integration-dev-http-requests_python36", "datadog_lambda": "X.X.X", "dd_trace": "X.X.X", "function_trigger.event_source": "sqs", "function_trigger.event_source_arn": "arn:aws:sqs:us-east-2:123456789012:my-queue"}, "metrics": {"system.pid": XXXX, "_sampling_priority_v1": 1}, "type": "serverless"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "GET", "http.url": "https://ip-ranges.datadoghq.com/", "http.status_code": "200"}, "metrics": {"_dd.measured": 1}, "type": "http"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "GET", "http.url": "https://ip-ranges.datadoghq.eu/", "http.status_code": "200"}, "metrics": {"_dd.measured": 1}, "type": "http"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 1, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "POST", "http.url": "https://api.datadoghq.com/api/v1/distribution_points", "error.msg": "'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte", "error.type": "builtins.UnicodeDecodeError", "error.stack": "Traceback (most recent call last):\n  File \"/opt/python/lib/python3.6/site-packages/ddtrace/contrib/requests/connection.py\", line 95, in _wrap_send\n    response = func(*args, **kwargs)\n  File \"/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py\", line 133, in _log_request\n    _print_request_string(request)\n  File \"/opt/python/lib/python3.6/site-packages/datadog_lambda/patch.py\", line 147, in _print_request_string\n    data_dict = json.loads(data)\n  File \"/var/lang/lib/python3.6/json/__init__.py\", line 349, in loads\n    s = s.decode(detect_encoding(s), 'surrogatepass')\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte\n"}, "metrics": {"_dd.measured": 1}, "type": "http"}]]}
END RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	
XRAY TraceId: XXXX	SegmentId: XXXX	Sampled: true	
