START RequestId: XXXX Version: $LATEST
{"m": "aws.lambda.enhanced.invocations", "v": 1, "e": XXXX, "t": ["region:us-east-1", "account_id:XXXX", "functionname:integration-dev-sync-metrics_python38", "resource:integration-dev-sync-metrics_python38", "cold_start:true", "memorysize:1024", "runtime:python3.8", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python38_2.XX.0"]}
2021-03-24 18:59:17.720 (-04:00)	76b33254-2fac-449d-8c46-7e7058bc58f0	[ERROR]	[dd.trace_id=144528841734297816 dd.span_id=8559620621396846711]	Error flushing metrics and events
Traceback (most recent call last):
  File "/opt/python/lib/python3.8/site-packages/datadog/threadstats/base.py", line 343, in flush
    self.reporter.flush_distributions(dists)
  File "/opt/python/lib/python3.8/site-packages/datadog/threadstats/reporters.py", line 24, in flush_distributions
    api.Distribution.send(distributions, compress_payload=self.compress_payload)
  File "/opt/python/lib/python3.8/site-packages/datadog/api/distributions.py", line 42, in send
    return super(Distribution, cls).send(
  File "/opt/python/lib/python3.8/site-packages/datadog/api/resources.py", line 82, in send
    return APIClient.submit(
  File "/opt/python/lib/python3.8/site-packages/datadog/api/api_client.py", line 162, in submit
    result = cls._get_http_client().request(
  File "/opt/python/lib/python3.8/site-packages/datadog/api/http_client.py", line 96, in request
    result = cls._session.request(
  File "/opt/python/lib/python3.8/site-packages/datadog_lambda/patch.py", line 112, in _wrap_requests_request
    return func(*args, **kwargs)
  File "/opt/python/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/lib/python3.8/site-packages/datadog_lambda/patch.py", line 133, in _log_request
    _print_request_string(request)
  File "/opt/python/lib/python3.8/site-packages/datadog_lambda/patch.py", line 147, in _print_request_string
    data_dict = json.loads(data)
  File "/var/lang/lib/python3.8/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byteEND RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	Init Duration: XXXX ms	
XRAY TraceId: XXXX	SegmentId: XXXX	Sampled: true	
START RequestId: XXXX Version: $LATEST
{"m": "aws.lambda.enhanced.invocations", "v": 1, "e": XXXX, "t": ["region:us-east-1", "account_id:XXXX", "functionname:integration-dev-sync-metrics_python38", "resource:integration-dev-sync-metrics_python38", "cold_start:false", "memorysize:1024", "runtime:python3.8", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python38_2.XX.0"]}
2021-03-24 18:59:19.154 (-04:00)	4c1081f8-c6eb-4c3c-9546-752a0004f69c	[ERROR]	[dd.trace_id=7659987519158096772 dd.span_id=11757457161935403993]	Error flushing metrics and events
Traceback (most recent call last):
  File "/opt/python/lib/python3.8/site-packages/datadog/threadstats/base.py", line 343, in flush
    self.reporter.flush_distributions(dists)
  File "/opt/python/lib/python3.8/site-packages/datadog/threadstats/reporters.py", line 24, in flush_distributions
    api.Distribution.send(distributions, compress_payload=self.compress_payload)
  File "/opt/python/lib/python3.8/site-packages/datadog/api/distributions.py", line 42, in send
    return super(Distribution, cls).send(
  File "/opt/python/lib/python3.8/site-packages/datadog/api/resources.py", line 82, in send
    return APIClient.submit(
  File "/opt/python/lib/python3.8/site-packages/datadog/api/api_client.py", line 162, in submit
    result = cls._get_http_client().request(
  File "/opt/python/lib/python3.8/site-packages/datadog/api/http_client.py", line 96, in request
    result = cls._session.request(
  File "/opt/python/lib/python3.8/site-packages/datadog_lambda/patch.py", line 112, in _wrap_requests_request
    return func(*args, **kwargs)
  File "/opt/python/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/lib/python3.8/site-packages/datadog_lambda/patch.py", line 133, in _log_request
    _print_request_string(request)
  File "/opt/python/lib/python3.8/site-packages/datadog_lambda/patch.py", line 147, in _print_request_string
    data_dict = json.loads(data)
  File "/var/lang/lib/python3.8/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byteEND RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	
XRAY TraceId: XXXX	SegmentId: XXXX	Sampled: true	
START RequestId: XXXX Version: $LATEST
{"m": "aws.lambda.enhanced.invocations", "v": 1, "e": XXXX, "t": ["region:us-east-1", "account_id:XXXX", "functionname:integration-dev-sync-metrics_python38", "resource:integration-dev-sync-metrics_python38", "cold_start:false", "memorysize:1024", "runtime:python3.8", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python38_2.XX.0"]}
2021-03-24 18:59:20.541 (-04:00)	9d8c230b-77c6-4939-af22-dff37dcc40c5	[ERROR]	[dd.trace_id=666 dd.span_id=14196266589707550623]	Error flushing metrics and events
Traceback (most recent call last):
  File "/opt/python/lib/python3.8/site-packages/datadog/threadstats/base.py", line 343, in flush
    self.reporter.flush_distributions(dists)
  File "/opt/python/lib/python3.8/site-packages/datadog/threadstats/reporters.py", line 24, in flush_distributions
    api.Distribution.send(distributions, compress_payload=self.compress_payload)
  File "/opt/python/lib/python3.8/site-packages/datadog/api/distributions.py", line 42, in send
    return super(Distribution, cls).send(
  File "/opt/python/lib/python3.8/site-packages/datadog/api/resources.py", line 82, in send
    return APIClient.submit(
  File "/opt/python/lib/python3.8/site-packages/datadog/api/api_client.py", line 162, in submit
    result = cls._get_http_client().request(
  File "/opt/python/lib/python3.8/site-packages/datadog/api/http_client.py", line 96, in request
    result = cls._session.request(
  File "/opt/python/lib/python3.8/site-packages/datadog_lambda/patch.py", line 112, in _wrap_requests_request
    return func(*args, **kwargs)
  File "/opt/python/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/lib/python3.8/site-packages/datadog_lambda/patch.py", line 133, in _log_request
    _print_request_string(request)
  File "/opt/python/lib/python3.8/site-packages/datadog_lambda/patch.py", line 147, in _print_request_string
    data_dict = json.loads(data)
  File "/var/lang/lib/python3.8/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byteEND RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	
XRAY TraceId: XXXX	SegmentId: XXXX	Sampled: true	
START RequestId: XXXX Version: $LATEST
{"m": "aws.lambda.enhanced.invocations", "v": 1, "e": XXXX, "t": ["region:us-east-1", "account_id:XXXX", "functionname:integration-dev-sync-metrics_python38", "resource:integration-dev-sync-metrics_python38", "cold_start:true", "memorysize:1024", "runtime:python3.8", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python38_2.XX.0"]}
2021-03-24 19:20:52.929 (-04:00)	e9903389-b747-419f-8e9f-fa7d49320306	[ERROR]	[dd.trace_id=2790261720198225597 dd.span_id=13477005725752197388]	Error flushing metrics and events
Traceback (most recent call last):
  File "/opt/python/lib/python3.8/site-packages/datadog/threadstats/base.py", line 343, in flush
    self.reporter.flush_distributions(dists)
  File "/opt/python/lib/python3.8/site-packages/datadog/threadstats/reporters.py", line 24, in flush_distributions
    api.Distribution.send(distributions, compress_payload=self.compress_payload)
  File "/opt/python/lib/python3.8/site-packages/datadog/api/distributions.py", line 42, in send
    return super(Distribution, cls).send(
  File "/opt/python/lib/python3.8/site-packages/datadog/api/resources.py", line 82, in send
    return APIClient.submit(
  File "/opt/python/lib/python3.8/site-packages/datadog/api/api_client.py", line 162, in submit
    result = cls._get_http_client().request(
  File "/opt/python/lib/python3.8/site-packages/datadog/api/http_client.py", line 96, in request
    result = cls._session.request(
  File "/opt/python/lib/python3.8/site-packages/datadog_lambda/patch.py", line 112, in _wrap_requests_request
    return func(*args, **kwargs)
  File "/opt/python/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/lib/python3.8/site-packages/datadog_lambda/patch.py", line 133, in _log_request
    _print_request_string(request)
  File "/opt/python/lib/python3.8/site-packages/datadog_lambda/patch.py", line 147, in _print_request_string
    data_dict = json.loads(data)
  File "/var/lang/lib/python3.8/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byteEND RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	Init Duration: XXXX ms	
XRAY TraceId: XXXX	SegmentId: XXXX	Sampled: true	
START RequestId: XXXX Version: $LATEST
{"m": "aws.lambda.enhanced.invocations", "v": 1, "e": XXXX, "t": ["region:us-east-1", "account_id:XXXX", "functionname:integration-dev-sync-metrics_python38", "resource:integration-dev-sync-metrics_python38", "cold_start:false", "memorysize:1024", "runtime:python3.8", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python38_2.XX.0"]}
2021-03-24 19:20:54.326 (-04:00)	de600536-a537-4e99-9424-de229781daa2	[ERROR]	[dd.trace_id=4549987215965899257 dd.span_id=17347583603786110858]	Error flushing metrics and events
Traceback (most recent call last):
  File "/opt/python/lib/python3.8/site-packages/datadog/threadstats/base.py", line 343, in flush
    self.reporter.flush_distributions(dists)
  File "/opt/python/lib/python3.8/site-packages/datadog/threadstats/reporters.py", line 24, in flush_distributions
    api.Distribution.send(distributions, compress_payload=self.compress_payload)
  File "/opt/python/lib/python3.8/site-packages/datadog/api/distributions.py", line 42, in send
    return super(Distribution, cls).send(
  File "/opt/python/lib/python3.8/site-packages/datadog/api/resources.py", line 82, in send
    return APIClient.submit(
  File "/opt/python/lib/python3.8/site-packages/datadog/api/api_client.py", line 162, in submit
    result = cls._get_http_client().request(
  File "/opt/python/lib/python3.8/site-packages/datadog/api/http_client.py", line 96, in request
    result = cls._session.request(
  File "/opt/python/lib/python3.8/site-packages/datadog_lambda/patch.py", line 112, in _wrap_requests_request
    return func(*args, **kwargs)
  File "/opt/python/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/lib/python3.8/site-packages/datadog_lambda/patch.py", line 133, in _log_request
    _print_request_string(request)
  File "/opt/python/lib/python3.8/site-packages/datadog_lambda/patch.py", line 147, in _print_request_string
    data_dict = json.loads(data)
  File "/var/lang/lib/python3.8/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byteEND RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	
XRAY TraceId: XXXX	SegmentId: XXXX	Sampled: true	
START RequestId: XXXX Version: $LATEST
{"m": "aws.lambda.enhanced.invocations", "v": 1, "e": XXXX, "t": ["region:us-east-1", "account_id:XXXX", "functionname:integration-dev-sync-metrics_python38", "resource:integration-dev-sync-metrics_python38", "cold_start:false", "memorysize:1024", "runtime:python3.8", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python38_2.XX.0"]}
2021-03-24 19:20:55.701 (-04:00)	f48c6e32-0bdc-4b64-af80-91f9e8e40316	[ERROR]	[dd.trace_id=666 dd.span_id=3255141880178267146]	Error flushing metrics and events
Traceback (most recent call last):
  File "/opt/python/lib/python3.8/site-packages/datadog/threadstats/base.py", line 343, in flush
    self.reporter.flush_distributions(dists)
  File "/opt/python/lib/python3.8/site-packages/datadog/threadstats/reporters.py", line 24, in flush_distributions
    api.Distribution.send(distributions, compress_payload=self.compress_payload)
  File "/opt/python/lib/python3.8/site-packages/datadog/api/distributions.py", line 42, in send
    return super(Distribution, cls).send(
  File "/opt/python/lib/python3.8/site-packages/datadog/api/resources.py", line 82, in send
    return APIClient.submit(
  File "/opt/python/lib/python3.8/site-packages/datadog/api/api_client.py", line 162, in submit
    result = cls._get_http_client().request(
  File "/opt/python/lib/python3.8/site-packages/datadog/api/http_client.py", line 96, in request
    result = cls._session.request(
  File "/opt/python/lib/python3.8/site-packages/datadog_lambda/patch.py", line 112, in _wrap_requests_request
    return func(*args, **kwargs)
  File "/opt/python/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/lib/python3.8/site-packages/datadog_lambda/patch.py", line 133, in _log_request
    _print_request_string(request)
  File "/opt/python/lib/python3.8/site-packages/datadog_lambda/patch.py", line 147, in _print_request_string
    data_dict = json.loads(data)
  File "/var/lang/lib/python3.8/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byteEND RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	
